# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function for quickly calculating model direction/agreement
#' @name ModelDir
#' @param x data
#' @param curr vector of current suitability
#' @param dir Improve or Decline
#' @return NumericVector
ModelDir <- function(x, Curr, dir) {
    .Call(`_ccissr_ModelDir`, x, Curr, dir)
}

gs2gw <- function(x, a, b) {
    .Call(`_ccissr_gs2gw`, x, a, b)
}

cmd_sum <- function(vals, cutoff) {
    .Call(`_ccissr_cmd_sum`, vals, cutoff)
}

SimGrowth <- function(DF, cmdMin, cmdMax, tempMin, tempMax, climLoss) {
    .Call(`_ccissr_SimGrowth`, DF, cmdMin, cmdMax, tempMin, tempMax, climLoss)
}

combCurr <- function(dat, wt) {
    .Call(`_ccissr_combCurr`, dat, wt)
}

NewSuitNoCurr <- function(x, vals) {
    .Call(`_ccissr_NewSuitNoCurr`, x, vals)
}

FeasSuit <- function(x, Curr, vals, CurrAdj) {
    .Call(`_ccissr_FeasSuit`, x, Curr, vals, CurrAdj)
}

stepDiff <- function(Year, NewSuit, Curr) {
    .Call(`_ccissr_stepDiff`, Year, NewSuit, Curr)
}

